- README.md
- bench.js
- example.js
- index.js
- node.js
- test/errors.test.js
- test/methods.test.js
- test/querystring.test.js
- test/server.test.js
- test/store.test.js
- Added a store object for every node
- Refactored `find` => *recursive* to *iterative* (better results for long paths)
- Updated `lookup` api, now accepts only `request` and `response` objects.
- Updated docs
@mcollina feedbacks?
> Added Store, refactored internals and updated api

- README.md
- index.js
- test/methods.test.js
- test/store.test.js
As titled.
In addition has been added a test case for the update of the store, the docs has been updated as well.
cc @mcollina
> Automatically decode the uri

- .travis.yml
- README.md
- index.js
- package.json
- test/methods.test.js
As titled, see https://github.com/yoshuawuyts/wayfarer/issues/57 for discussion :)
cc @mcollina
> Safe decodeURIComponent

- .travis.yml
- index.js
- node.js
- test/errors.test.js
- test/methods.test.js
- test/server.test.js
Finally found a fix for #5 without compromising the performances! 🎉
> Catch all wildcard

- node.js
- test/methods.test.js
Fixed wrong behaviour discovered in https://github.com/fastify/fastify/pull/113.
> Fix common prefix

- README.md
- index.js
- node.js
- test/pretty-print.test.js
A nice utility that you can use for debugging :)
> Pretty print

- README.md
- index.js
- test/pretty-print.test.js
- test/shorthands.test.js
> Shorthand Methods

- index.js
Node 6.11
Before:
```
lookup static route x 4,194,264 ops/sec ±0.83% (93 runs sampled)
lookup dynamic route x 690,927 ops/sec ±0.83% (91 runs sampled)
lookup long static route x 2,040,913 ops/sec ±0.90% (90 runs sampled)
find static route x 5,143,679 ops/sec ±0.89% (88 runs sampled)
find dynamic route x 705,003 ops/sec ±0.93% (88 runs sampled)
find long static route x 2,425,694 ops/sec ±1.02% (89 runs sampled)
```
After:
```
lookup static route x 20,374,370 ops/sec ±1.45% (89 runs sampled)
lookup dynamic route x 701,705 ops/sec ±1.01% (90 runs sampled)
lookup long static route x 4,815,807 ops/sec ±2.82% (91 runs sampled)
find static route x 28,975,395 ops/sec ±1.01% (90 runs sampled)
find dynamic route x 723,708 ops/sec ±0.87% (91 runs sampled)
find long static route x 7,572,324 ops/sec …
```
> Avoid try catch for a 5x speedup

- example.js
Noticed when I copy & pasted output url
> fixed typo    ¯\_(ツ)_/¯

- README.md
- index.js
- test/errors.test.js
- test/methods.test.js
- test/shorthands.test.js
> Added support for multiple methods.

- README.md
- index.js
- test/methods.test.js
Add `.off(method, path)` method.
- https://github.com/delvedor/find-my-way/issues/40
> feat(off): add off feature

- README.md
- index.js
- test/max-param-length.test.js
> Added maxParamLength option

- README.md
> Updated regex docs

- index.js
- node.js
Optimized existence checks and object lookups.
*This branch:*
```
lookup static route x 29,182,417 ops/sec ±1.19% (87 runs sampled)
lookup dynamic route x 1,468,042 ops/sec ±1.28% (86 runs sampled)
lookup dynamic multi-parametric route x 819,827 ops/sec ±1.26% (90 runs sampled)
lookup dynamic multi-parametric route with regex x 792,738 ops/sec ±0.56% (92 runs sampled)
lookup long static route x 3,332,216 ops/sec ±1.05% (91 runs sampled)
find static route x 29,208,520 ops/sec ±1.01% (87 runs sampled)
find dynamic route x 1,560,609 ops/sec ±1.20% (83 runs sampled)
find dynamic multi-parametric route x 847,141 ops/sec ±1.07% (88 runs sampled)
find dynamic multi-parametric route with regex x 827,792 ops/sec ±0.82% (91 runs sampled)
find long static route x 4,145,462 ops/sec ±1.07% (89 runs …
```
> Optimized existence checks

- index.js
- test/methods.test.js
Fixed bug found in https://github.com/fastify/fastify/pull/823 and https://github.com/fastify/fastify/issues/824.
> Fix unsupported methods

- .gitignore
- README.md
- index.js
- node.js
- package.json
- test/methods.test.js
- test/shorthands.test.js
> Use http methods

- bench.js
- example.js
- index.js
- node.js
- package.json
- test/issue-67.test.js
As titled.
The benchmarks are almost the same except for the long static route, with this refactor we gain around 400-500k ops/sec more.
We must figure out a way to optimize the dynamic route handling.
cc @nwoltman
> Refactored Node object

- index.js
- test/querystring.test.js
> Solve issue #76

- README.md
`res.send` is not a valid function, it should be `res.end`.
Thank you!
> fix README send function

- index.js
- test/for-in-loop.test.js
Never forget this, if you use for..in
> Prevent TypeError: m.toLowerCase is not a function

- README.md
> Update readme for explaining better the route order

- index.d.ts
- package.json
- test/types/index.ts
- test/types/tsconfig.json
Hi there, I'm considering using this library in my project and thought I'd contribute my typings for it. These typings should work for TypeScript version 3.x.x
> chore: add typescript typings

- index.js
- test/case-insesitive.test.js
- test/full-url.test.js
Fixes https://github.com/fastify/fastify/issues/1374.
Benchmarks stays consistent before and after.
> Fix fastify 1374

- README.md
- test/routes-registered.test.js
> Expose routes registered in docs

- README.md
> Fixes readme typo

- index.js
- test/case-insensitive.test.js
> Fix uppercase static path

- .taprc
- azure-pipelines.yml
- index.js
- package.json
- test/errors.test.js
- test/version.custom-versioning.test.js
This is a semver-major change, preparing for Fastify v3.
> Updated dependencies

- node.js
> Fix #186 bug

- index.d.ts
- test/types/router.test-d.ts
Update ``prettyPrint`` types for the feature added with #185
> add includeMeta to prettyPrint options

- lib/constrainer.js
- test/http2/constraint.host.test.js
> add :authority to host constraint to support http2

- lib/constrainer.js
- test/http2/constraint.host.test.js
As discussed in fastify/fastify#3504, This PR applies the changes made in delvedor/find-my-way#214 to v4
> Add :authority to host constraint to support http2 v4

- test/regex.test.js
> Add test for issue #204

- handler_storage.js
- index.js
- lib/pretty-print.js
Refactored and optimized handler storage.
> Refactored handler storage

- handler_storage.js
- index.js
> Optimized creating result params object

- index.d.ts
- test/types/router.test-d.ts
> Change lookup result type to any

- README.md
- index.d.ts
- index.js
- lib/constrainer.js
- test/constraint.custom-versioning.test.js
- test/constraint.custom.test.js
- test/constraints.test.js
- test/types/router.test-d.ts
> Add addConstraintStrategies method

- custom_node.js
- index.js
- test/issue-238.test.js
Fixed https://github.com/fastify/fastify/issues/4030
> Fix multi-parametrical nodes with diff static ending

- lib/pretty-print.js
fixes lgtm alert https://lgtm.com/projects/g/delvedor/find-my-way/?mode=tree&ruleFocus=7900088
> remove unused parameter

- custom_node.js
> refactor: typo chatCode -> charCode

- README.md
I have restructured the documentation a bit and added a TOC.
> restructure docs and add TOC

- index.js
- test/issue-28.test.js
Close #304 https://github.com/fastify/fastify/issues/4306
> Add error for wildcard route with suffix

- README.md
- index.js
- lib/constrainer.js
- test/constraint.custom.async.test.js
- test/lookup-async.test.js
> feat: add async custom constraints support

- README.md
I have only swapped 2 sentences so that the sentences match the corresponding code example.
> swap sentences in docs

- README.md
> fix ci badge

- package.json
> chore(package): update `engines.node` to >=20
