- index.js
Testing benchmark on node 7.10 : 
Before : 
lookup static route x 14,919,746 ops/sec ±0.77% (90 runs sampled)
lookup dynamic route x 662,481 ops/sec ±0.63% (94 runs sampled)
lookup long static route x 2,311,837 ops/sec ±0.98% (90 runs sampled)
find static route x 28,791,481 ops/sec ±0.88% (87 runs sampled)
find dynamic route x 732,577 ops/sec ±0.64% (94 runs sampled)
find long static route x 6,701,436 ops/sec ±0.75% (91 runs sampled)
After :
lookup static route x 16,330,523 ops/sec ±0.81% (91 runs sampled)
lookup dynamic route x 980,184 ops/sec ±0.61% (94 runs sampled)
lookup long static route x 3,957,358 ops/sec ±0.70% (90 runs sampled)
find static route x 29,006,918 ops/sec ±0.83% (94 runs sampled)
find dynamic route x 1,047,862 ops/sec ±0.53% (92 runs sampled)
find long static route x …
> replace string equality with charCode equality

- index.js
avoid unecessary slice of url and I think it's also easier to read.
Using node JS 7.10 on mac OS :
From
lookup static route x 16,199,148 ops/sec ±0.61% (92 runs sampled)
lookup dynamic route x 945,503 ops/sec ±0.54% (93 runs sampled)
lookup long static route x 4,024,544 ops/sec ±0.47% (93 runs sampled)
To
lookup static route x 21,672,160 ops/sec ±0.72% (91 runs sampled)
lookup dynamic route x 1,039,106 ops/sec ±0.92% (92 runs sampled)
lookup long static route x 4,241,299 ops/sec ±0.59% (92 runs sampled)
> optimize lookup

- README.md
use the correct domain for wikipedia in order to avoid certificate issue in the browser.
> use wikipedia.org instead of wikipedia.com

- README.md
- index.js
- node.js
- test/regex.test.js
With this PR we introduce a basic support for regex in urls (#15).
Example:
```js
router.on('GET', '/test/:id(^\\d+$)', (req, res, params) => {
// your logic
})
```
Currently the following is not supported:
`/test/:id(^\\d+$).png` and `/test/:id(^\\d+$)-:param(^\\d+$)`.
In Express [path-to-regexp](https://github.com/pillarjs/path-to-regexp) is used, but is not working fine for us since we are using a completely different data structure for performances reasons (same reason we are avoiding regex in the first place).
Feedbacks?
If you have some suggestion to support also the other cases, please let me know.
*ps at the moment this pr is not introducing any performances regression.*
> Basic regex support

- index.js
- node.js
As titled, there is a slightly improvements in the performances, any suggestion?
Before:
```
lookup static route x 21,752,581 ops/sec ±0.75% (90 runs sampled)
lookup dynamic route x 707,120 ops/sec ±1.14% (91 runs sampled)
lookup long static route x 2,894,137 ops/sec ±7.11% (86 runs sampled)
find static route x 31,506,022 ops/sec ±1.12% (87 runs sampled)
find dynamic route x 705,175 ops/sec ±0.85% (88 runs sampled)
find long static route x 3,994,827 ops/sec ±10.60% (83 runs sampled)
```
After:
```
lookup static route x 21,755,241 ops/sec ±0.83% (89 runs sampled)
lookup dynamic route x 717,386 ops/sec ±1.07% (90 runs sampled)
lookup long static route x 2,768,482 ops/sec ±6.72% (86 runs sampled)
find static route x 31,849,514 ops/sec ±0.79% (89 runs sampled)
find dynamic route x 737,994 …
```
> Call find only one time

- README.md
- node.js
- test/methods.test.js
As titled.
In this way we can support something like the following:
```js
const router = FindMyWay()
router.on('GET', '/test/:id', () => {
throw new Error('wrong handler')
})
router.on('GET', '/test/hello', () => {
console.log('inside correct handler')
})
router.lookup({ method: 'GET', url: '/test/hello' }, null)
```
Since this is an operation performed during the creation of the internal tree, the performances should not be affected.
> Static nodes should be inserted before parametric

- README.md
- bench.js
- index.js
- test/issue-17.test.js
Detect multi parametric path (new nodeType=4)
Handle lookup for multi parametric path
Unit test issue #17
> Hanlde multi-parametric route (issue #17)

- index.js
- test/issue-17.test.js
Fix regression reported in https://github.com/delvedor/find-my-way/pull/27#issuecomment-333331583.
@AVVS, I'm sorry for the leaked breaking change.
> Fix regression issue #17

- index.js
- test/errors.test.js
- test/regex.test.js
As titled.
An url should start with `/` or `*` and could not be empty.
>  Added url validations

- README.md
- index.js
- node.js
- test/issue-28.test.js
- test/methods.test.js
After a lot of work I come up with two solutions:
1. `find2` is a recursive function, we cover all the test cases but we are slower, around 1%-5% leff compared to the iterative version
2. `find` is iterative, we have two trees, one for the static/parametric routes and one for the wildcards. If the static/parametric fails if we know that there is a wildcard route we search it inside the wildcard tree. All the changes inside the `insert` and `_insert` function has been done to support this.
Sorry about the following, two different PRs were a little bit hard to handle:
If you want to test the recursive function:
1. rename `find2`in `find` and viceversa.
2. uncomment line 141
As you can see the recursive version works in all the cases, while the iterative fails in case of nested static nodes. …
> Find refactor

- index.js
- node.js
- test/methods.test.js
As titled.
In some edge cases could happen that we overwrite the `paramsObj` stored in the node map object, and because of the reference of the object an user could have an hard time to figure out what is happening.
This pr fixed that.
> Fixed wrong params object reference

- README.md
- index.js
- test/methods.test.js
- test/server.test.js
This PR implements the logic described in https://github.com/fastify/fastify/issues/584#issuecomment-355134797
```js
const router = require('find-my-way')({
trimTrailingSlash: true
})
function handler (req, res, params) {
res.send('foo')
}
// maps "/foo/" and "/foo" to `handler`
router.on('GET', '/foo/', handler)
```
> Add support for ignoring trailing slashes

- index.js
- test/errors.test.js
This changes the error message to include the full route path. This makes it easier to understand which route was declared twice.
> Improve error message when route is already declared

- index.js
- test/errors.test.js
I noticed that one of the test cases in `errors.test.js` would fail when tested with `ignoreTrailingSlash=true`.
This adds a bunch of error tests for when `ignoreTrailingSlash` is `true` and fixes the `router.on()` code so that all the tests pass. This also speeds up validation a bit since the same parameters won't be validated multiple times when the input `method` is an array.
> Fix router.on() parameter validation

- index.js
- node.js
This PR replaces all of the instances like `node.kind === 0` with `node.kind === NODE_TYPES.STATIC`. This is clearer to the reader, and thus to people trying to contribute to the project.
My system is a mid-2012 MacBook Pro, so it isn't very fast. But I don't see any real discrepancy in the benchmarks:
**master:**
```
lookup static route x 22,606,815 ops/sec ±1.10% (85 runs sampled)
lookup dynamic route x 1,406,844 ops/sec ±0.99% (89 runs sampled)
lookup dynamic multi-parametric route x 776,795 ops/sec ±0.99% (87 runs sampled)
lookup dynamic multi-parametric route with regex x 689,269 ops/sec ±0.99% (89 runs sampled)
lookup long static route x 2,919,538 ops/sec ±1.03% (89 runs sampled)
find static route x 27,170,227 ops/sec ±0.89% (87 runs sampled)
find dynamic route x 1,490,351 ops/sec …
```
> Use constants for node types instead of magic numbers

- README.md
- test/issue-44.test.js
The caveat was fixed by #45 and #57.
> Remove old caveat

- index.js
- test/issue-59.test.js
How this fix works:
When matching a path to a prefix in a `node`, this part of the code finds the longest common prefix. Before it would only look for the next part of the path if the path matched the entire prefix, otherwise it would continue matching the same path. This was wrong because then this would happen:
```
path = 'bulk'
prefix = 'b/'
commonPrefix = 'b'
-- does not update path --
finds child with prefix = 'bulk'
goes back to the top and matches 'bulk'
return handler for '/b/bulk'
```
With this fix it does this:
```
path = 'bulk'
prefix = 'b/'
commonPrefix = 'b'
update path = 'ulk'
no children match 'ulk'
return null
```
<details>
<summary>benchmarks</summary>
**before**
```
lookup static route x 26,167,641 ops/sec ±1.42% (89 runs sampled)
lookup dynamic route x 1,568,707 ops/sec …
```
> Fix issue looking up routes that don't exist

- index.js
- node.js
- test/issue-67.test.js
The `Node#find()` method was trying to take a shortcut by matching against the node's "label" (the first character of the prefix). This fixes route matching issues by matching against the entire prefix when the node is a static node.
Fixes #67
This is the correct fix for #59/#60
<details>
<summary>Benchmark</summary>
**before**
```
lookup static route x 29,941,458 ops/sec ±2.24% (90 runs sampled)
lookup dynamic route x 1,707,649 ops/sec ±1.97% (94 runs sampled)
lookup dynamic multi-parametric route x 974,717 ops/sec ±0.43% (94 runs sampled)
lookup dynamic multi-parametric route with regex x 889,377 ops/sec ±0.52% (96 runs sampled)
lookup long static route x 2,713,562 ops/sec ±0.42% (94 runs sampled)
find static route x 35,555,376 ops/sec ±0.81% (96 runs sampled)
find dynamic route x …
```
> Fix route matching issue with common prefix

- index.js
- test/issue-62.test.js
- test/issue-63.test.js
Fixes #63 by throwing a `TypeError` error if the regexp expressions is wrong
Fixes #62
> Invalid expressions for regexp parameters

- index.js
- test/methods.test.js
Currently, looking up an unsupported is throwing an error because the method isn't in the `handlers` object, so trying to get a handler from the `handlers` object will return `undefined` (and currently only `null` is being handled).
> Fix lookups of unsupported methods

- .travis.yml
- README.md
- index.js
- package.json
- test/issue-62.test.js
- test/regex.test.js
Now `find-my-way` detects potentially catastrophic exponential-time regular expressions thanks to [`safe-regex`](https://github.com/substack/safe-regex).
This check can be disabled with `{ allowUnsafeRegex: true }`.
cc @hekike
> Safe regex by default

- node.js
Some libraries add function to (Iteratable) Array.prototype and for(var .. in ..) loop will iterate over those function and code will throw syntax error if the function clousure has more than one line.
> prevent looping over prototype chain

- README.md
- index.js
- test/case-insesitive.js
- test/case-insesitive.test.js
See https://github.com/fastify/fastify/issues/1007.
@thearegee would this work for you?
> Add an option to disable case-sensitive routing

- node.js
- package.json
- test/issue-93.test.js
- Fix issue 93
- Add a test case for that
- Update dependencies by the way (no break change)
> fix: Fix `versions` parameter not work in Node constructor

- node.js
- package.json
- test/issue-110.test.js
This is causing issues resulting in nodes not having a parametric brother as witnessed in #110 
`node bench.js` result:
**Master**
```
lookup static route x 36,805,474 ops/sec ±1.94% (83 runs sampled)
lookup dynamic route x 3,062,199 ops/sec ±1.85% (87 runs sampled)
lookup dynamic multi-parametric route x 1,681,604 ops/sec ±1.76% (85 runs sampled)
lookup dynamic multi-parametric route with regex x 1,319,392 ops/sec ±1.05% (88 runs sampled)
lookup long static route x 2,975,863 ops/sec ±0.85% (90 runs sampled)
lookup long dynamic route x 2,116,684 ops/sec ±0.90% (91 runs sampled)
lookup static versioned route x 7,842,228 ops/sec ±0.87% (91 runs sampled)
find static route x 38,501,099 ops/sec ±0.69% (94 runs sampled)
find dynamic route x 4,113,594 ops/sec ±0.60% (93 runs sampled)
find …
```
> Falling back to node's parametricBrother

- bench.js
See the added comment for context. This change results in the benchmark suite taking a lot longer to run, but I find the tradeoff acceptable in my recent use cases.
I don't feel super strongly about this as I can always override this locally, but maybe that's a better default value for everyone?
> increase min samples for benchmark suite

- index.js
- test/case-insensitive.test.js
This PR has the same goal as https://github.com/delvedor/find-my-way/pull/99, but is solving the problem using a different approach in an effort to get a better performance profile.
Using node v10.14.1 I get the following results on the current tip of the master branch:
```
$ node bench.js 
lookup static route x 47,169,425 ops/sec ±0.44% (92 runs sampled)
lookup dynamic route x 3,518,794 ops/sec ±1.27% (94 runs sampled)
lookup dynamic multi-parametric route x 1,959,970 ops/sec ±1.18% (91 runs sampled)
lookup dynamic multi-parametric route with regex x 1,485,289 ops/sec ±1.04% (95 runs sampled)
lookup long static route x 3,359,776 ops/sec ±0.51% (93 runs sampled)
lookup long dynamic route x 2,326,569 ops/sec ±0.88% (94 runs sampled)
lookup static versioned route x 8,826,650 ops/sec ±0.36% …
```
> preserve param values case in case insensitive mode

- node.js
- test/pretty-print.test.js
fix #129
It outputs the following:
> fix prettyPrint indent

- README.md
- index.js
- test/on-bad-url.test.js
Now `find-my-way` offers the support for a separate handler in case of a bad url. If it's not configured, the behavior will be the same as before, which means calling the `defaultRoute` in case of the `lookup` and returning `null` in case of `find`.
Usage:
```js
const router = require('find-my-way')({
onBadUrl: (path, req, res) => {
res.statusCode = 400
res.end(`Bad path: ${path}`)
}
})
```
Related: https://github.com/fastify/fastify/issues/1884
> Added support for onBadUrl

- index.js
- test/issue-145.test.js
Fixes #145 
Still working on it
> No match path param with ignoreTrailingSlash

- index.js
- test/issue-154.test.js
In #155 we have introduces a version check that is to strict and it's breaking Fastify [here](https://github.com/fastify/fastify/blob/521781db9f25eb5dfd5b61f19b2f0fc0137ee913/lib/route.js#L221).
This fix relaxes the check as the rest of the code does not handle undefined versions.
> Relax version check

- index.js
- test/path-params-match.test.js
For [node-restify](https://github.com/restify/node-restify#supported-node-versions), Node 8.x is the supported version, so I cherry-pick a commit(#159 ) to 2.x branch. Thanks.
> Fix path params match issue (#159)

- bench.js
- index.js
- lib/pretty-print.js
- node.js
- test/pretty-print.test.js
This makes pretty printing annoying, but increases performance!
With n trees instead of one tree, each tree is only split for handlers it actually has, so for HTTP verbs like POST or PUT that tend to have fewer routes, the trees are smaller and faster to traverse. For the HTTP GET tree, there are fewer nodes and I think better cache locality as that tree is traversed the most often. Each verb doesn't pay any traversal penalty for the other trees' size. This also results in more instances of more selective version stores, which means traversing them should be faster at the expense of a bit more memory consumption.
This also makes the constraints implementation (see #166) easier, and prevents bugs like #132, and avoids the extra checks we have to do to fix that bug.
This also prevents tree …
> Switch to using one tree per method instead of a map

- README.md
- index.js
- lib/accept-version.js
- test/version.default-versioning.test.js
This pull request disables the automatic route versioning unless a user has configured at least once a route with the version option.
> Enable versioning on demand

- node.js
- test/issue-182.test.js
Related to [fastify/2938](https://github.com/fastify/fastify/issues/2938)
Caused by not setting method property when splitting node
> fix prettyPrint undefined method

- README.md
- index.js
- lib/pretty-print.js
- test/pretty-print.test.js
I found some unexpected behaviour in the way routes were displayed while I was testing this feature addition for `fastify-autoload` (https://github.com/fastify/fastify-autoload/pull/134)
The route parameters weren't being properly placed when drawing the tree if there was no root item. An example can be found in the PR linked above. I added a test for a specific instance where I was able to get it to break.
I have also added an additional tree-drawing function which uses the `findMyWay.routes` array instead of the radix tree, as it might be more intuitive to some users because it doesn't break trees by common prefixes (e.g. `home, homer, honour` in place of `ho->me, ho->me->r, ho->nour`)
If the added function is appropriate, I will add some tests for it.
> Pretty print bugfix and revision

- README.md
- index.js
- lib/pretty-print.js
- test/pretty-print.test.js
Re: https://github.com/fastify/fastify/issues/2993
Adds ability to display hooks in `prettyPrint` output.
```
commonPrefix: false
├── /pages (GET)
│   • (onTimeout) ["timeoutHook"]
│   • (onRequest) ["anonymous","authenticate_token"]
│   ├── / (GET)
│   │   • (onTimeout) ["timeoutHook"]
│   │   • (onRequest) ["anonymous","authenticate_token"]
│   ├── /:id (GET)
│   │   • (onTimeout) ["timeoutHook"]
│   │   • (onRequest) ["anonymous","authenticate_token"]
│   │   └── / (GET)
│   │       • (onTimeout) ["timeoutHook"]
│   │       • (onRequest) ["anonymous","authenticate_token"]
│   ├── /new (POST)
│   │   • (onTimeout) ["timeoutHook"]
│   │   • (onRequest) ["anonymous","authenticate_token"]
│   ├── /testing (GET) {"version":"1.0"}
│   │   • (onTimeout) ["timeoutHook"]
│   │   • (onRequest) …
```
> Feature: adding support to display fastify hooks

- index.js
- test/fastify-issue-3129.test.js
Fixes: https://github.com/fastify/fastify/issues/3129
Before
```
lookup static route x 60,585,458 ops/sec ±0.41% (590 runs sampled)
lookup dynamic route x 3,180,845 ops/sec ±0.34% (592 runs sampled)
lookup dynamic multi-parametric route x 1,888,387 ops/sec ±0.18% (592 runs sampled)
lookup dynamic multi-parametric route with regex x 1,372,640 ops/sec ±0.22% (592 runs sampled)
lookup long static route x 3,070,287 ops/sec ±0.24% (589 runs sampled)
lookup long dynamic route x 2,317,857 ops/sec ±0.30% (590 runs sampled)
lookup static route on constrained router x 17,111,003 ops/sec ±0.80% (570 runs sampled)
lookup static versioned route x 2,786,721 ops/sec ±0.42% (589 runs sampled)
lookup static constrained (version & host) route x 2,759,036 ops/sec ±0.42% (589 runs sampled)
find static route …
```
> fix: fastify issue 3129

- index.js
- test/issue-17.test.js
Closes #192 
Implements `.` as a separator between route params (similar to how `-` works), PR also refactors all `-` tests to test for `.` too.
> Implement '.' separator in parametric routes

- lib/constrainer.js
- node.js
- test/constraint.custom.test.js
- test/constraint.default-versioning.test.js
Fixes #196
mustMatchWhenDerived strategies ensure that requests that pass a value for the constraint (like a version number) should only match routes that are constrained using that strategy. This avoids invoking unconstrained, unversioned routes for requests that are versioned. find-my-way has supported this for a while, but all the work to add custom constraint strategies broke this support in a case where both unconstrained and constrained routes were added for the same path. This fixes the tests to exercise that case and ensures the fast constraint matcher system doesn't allow unconstrained routes to match the mustMatchWhenDerived strategies!
This also fixes a bug where mustMatchWhenDerived constraints need to be used by a route before they start taking effect. 
For these, we need to …
> Fix mustMatchWhenDerived for route nodes with both unconstrained and constrained routes 

- custom_node.js
- test/issue-104.test.js
- test/issue-175.test.js
Hi, please don't judge me too hard since it's my first contribution here. I think the problem is that the `parametricBrother` field can be set even if `child.prefix` starts with `":"`. In this case, these are two colons in a row, which should be parsed as a simple path, and not as a path with a parameter. I'm not sure that it's the best solution, but it works, so I decided to create a PR.
> fix: double colon route issue (#219)

- custom_node.js
- index.js
- test/issue-221.test.js
The problem was that after switching from static route to parametric brother route it was trying to restore the previous path by searching the last `/` symbol. It means that if I have two routes `/static-test` and `/static-:param` and if I try to find `/static-test1`, after failing with static route it will stitch to parametric route and pass `static-test1` as a param instead of `test1`.
I fixed it by creating a stack where I put the context (the current position in the path and the parameters already found) every time I meet a node that has a parametric brother. When I need to switch to a parametric brother route I just get a context from the top of the stack.
Another thing that I changed here is that I added a parametric brother route not only for static routes but for all routes.
> fix: parametric brother path extraction (#222)

- node.js
- test/issue-104.test.js
- test/issue-175.test.js
Hi, although the double colon route issue (#219) is already fixed by (#220) and released in v5.1.1.
However, since I'm using `fastify`, which is currently using the 4.x version of `find-my-way`.
So I decided to cherry-pick #220 and create a PR.
- fastify/fastify#3550
> fix: double colon route issue (#219) for 4.x branch

- bench.js
When I tried to optimize the find method, I was confused. I made changes that were supposed to speed up the algorithm, but they only made it slower for short static routes. It turns out that `/` route is a super special case, cause you get the results immediately from the root node without using the searching algorithm. If you try to search the path that contains only one more symbol `/a`, you will get at least twice a worse result. IMHO, when we test the find method we want to see results for some average, but not for the extreme case.
> change path for short static route bench

- custom_node.js
- index.js
I refactored the find method. The main things that were changed:
- removed double path/prefix checking (in the find and findMatchingChild methods)
- removed unnecessary path splitting, I replaced it on just path pointer
- a bunch of other small optimizations
> Optimize find method

- custom_node.js
- index.js
It seems like it checks constraints twice: in the findMatchingChild function and in the find function.
> Removed unnecessary constraints check

- bench-thread.js
- bench.js
> Run benchmarks in separate threads

- custom_node.js
- index.js
- test/issue-28.test.js
> Fixed wildcard routes fallback

- custom_node.js
- index.js
- lib/pretty-print.js
- test/issue-241.test.js
Fixed #241 
This is not the best solution, but I don't know how to fix it perfectly right now.
> Fix double colon and parametric node collision

- custom_node.js
- index.js
- test/issue-17.test.js
- test/issue-238.test.js
Fixed #235 #238
The main problem with multi-parametrical nodes is that we can't easily describe the rules of how should it be parsed. Thanks for @mcollina, he said that if I have an unclear case it should work as the [path-to-regexp](https://github.com/pillarjs/path-to-regexp) library does https://github.com/delvedor/find-my-way/issues/238#issuecomment-1021464532. The path-to-regexp converts the hole path to the regexp, so a multi-parametric path is also parsed as a regex. The main idea of this solution is to convert the multi-parametrical part of the path to the regexp. Seems like it's the only way to make it work properly.
**Important point: It doesn't convert the whole path to the regexp (as path-to-regexp does), only the part of the path between two '/' if it contains multiple params …
> Fixed parameters parsing

- README.md
- lib/strategies/accept-host.js
- lib/strategies/accept-version.js
- package.json
- test/host-storage.test.js
I optimized the version constraint strategy and removed empty and delete methods from the strategy interface. I don't know why we need them.
> Optimize constraints' strategies

- .github/workflows/node.js.yml
Bump GitHub Actions to their latest major versions. Main change is they're now using Node 16 instead of 12.
> build(deps-dev): bump github actions

- custom_node.js
- index.js
- test/issue-104.test.js
Just small refactoring. I split the insert method into three methods for each type of node (static/parametric/wildcard). IMHO it makes the code more self-explaining.
> Define insert method for each node type

- custom_node.js
- handler_storage.js
- index.js
- lib/pretty-print.js
- test/issue-104.test.js
I refactored the Node entity:
- Divided the Node into the three different classes: StaticNode, ParametricNode, WildcardNode; each of these classes has a different set of properties and methods
- Moved everything related to handlers and matching constraints to the separate entity: HandlerStorage
> Create class for each node type

- index.js
- test/errors.test.js
- test/methods.test.js
I changed ignoring trailing slash behavior. Instead of creating two duplicated routes (with slash and without), it just removes the trailing slash. Performance is the same, but it's much easier to maintain. It will affect the `routes` field. There will be only one trimmed route instead of two. The `route` field should be used only for debugging, so I don't know if it's a breaking change.
> Change ignore trailing slash behavior

- handler_storage.js
- index.js
- test/issue-254.test.js
> Fix constrainer overwrite

- package.json
The build on the CI failed due to a conflict in tap dependencies. I updated tap dependency to the last major version.
https://github.com/delvedor/find-my-way/runs/6140478918?check_suite_focus=true
> Update tap dependency

- README.md
- index.d.ts
- index.js
- test/issue-247.test.js
> Add router.off method support filter

- index.js
- test/matching-order.test.js
As far as I understand from the documentation, the route with the longest match of the static part has a higher priority.
https://github.com/delvedor/find-my-way#match-order
So for the `/foo/bar/static` path, `/foo/bar/*` route has higher priority than `/foo/:param/static`. If it's correct, it wasn't working for some cases.
> Fix matching order

- package.json
- test/server.test.js
Since the [request](https://www.npmjs.com/package/request) has been deprecated, I decided to remove it from dependencies.
> Remove request dev dependency

- .github/workflows/node.js.yml
Should we just add v18, or replace v17?
> Add Node.js v18

- .github/workflows/node.js.yml
Declares the minimum [permissions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) for CI workflows to run at the workflow level, following principle of least privilege; see [related GitHub security post](https://securitylab.github.com/research/github-actions-building-blocks/)
> ci: reduce workflow permissions to minimum

- bench-thread.js
- bench.js
Benchmark refactoring:
- Updated benchmarks paths. All benchmark test routes have different paths and it takes significant time to iterate a path char by char. So some test cases can look really slow, not for the reason we are trying to test, but just because they have lost static prefix. I made paths the same where it makes sense, so it's easier to compare benchmarks between themselves.
- Removed find method benchmarks. Almost all find method benchmarks are duplicating lookup benchmarks. They have some sense because lookup adds some overhead by deriving constraints and calling a handler. But since we use an empty handler and almost empty constraint this overhead is really small and constant. From my experience find method benchmarks don't give any new information, after running lookup …
> Normalize benchmark paths

- bench-cmp.js
- package.json
Added two new commands for benchmarking.
- `bench:cmp` - allows to choose two branches, run benchmarks and compare results.
- `bench:cmp:ci` - runs `bench:cmp` with default params current branch as a "new feature" branch and main branch.
If the difference between benchmarks is more or less than the threshold = 5%, it will emphasize the benchmark result with green or red color. 
selecting branches:
`bench:cmp:ci` output example:
> Add comparison of benchmarks results on different branches

- index.js
- lib/url-sanitizer.js
- package.json
- test/custom-decode-uri.test.js
- test/issue-234.test.js
Fix #234 and a bunch of optimization to make it work as fast as possible.
> Fix parameters decoding

- README.md
- index.d.ts
- index.js
- lib/url-sanitizer.js
- test/custom-querystring-parser.test.js
- test/methods.test.js
- test/querystring.test.js
- test/store.test.js
We are already searching the querystring in the path and are spending some time on it. I want to pass the querystring to the handler instead of parsing it again in the handler. The querystring would be passed to the handler as a new argument.
\+ find-my-way handle ';' as a querystring start symbol and fastify doesn't.
The changes to the fastify:
https://github.com/ivan-tymoshenko/fastify/commit/00087f04117844ec7be7b23a9e2d0d8fe4b12e2c
Benchmarks:
In the main branch, I added a handler that parses querystring in the same way as fastify does 
(https://github.com/fastify/fastify/blob/0a4649f504bd466ce7dd37b510832746b213b2d4/lib/route.js#L377) and compared it with parsing a querystring natively in the find-my-way.
Handler in the main branch:
```js
findMyWay.on(method, url, (req) => {
const …
```
> Add querrystring parser

- handler_storage.js
- lib/constrainer.js
- lib/pretty-print.js
- test/constraint.default-versioning.test.js
- test/constraints.test.js
- test/issue-254.test.js
The is a bug with constraints with the mustMatchWhenDerived option.
How it should work. If you have a constraint with the mustMatchWhenDerived option in your request you can match only the routes that have and match this constraint.
How it works. If you have a constraint with the mustMatchWhenDerived option in your request you can match the routes that have and match this constraint or other routes that have any other different constraints.
There are some tests that test wrong behavior:
https://github.com/delvedor/find-my-way/blob/a59117d0daf351429919d586e5edea4ef6d2a14b/test/constraints.test.js#L62
https://github.com/delvedor/find-my-way/blob/a59117d0daf351429919d586e5edea4ef6d2a14b/test/constraints.test.js#L75
https://github.com/delvedor/find-my-way/blob/a59117d0daf351429919d586e5edea4ef …
> Fixed must match constraints check

- index.js
- lib/url-sanitizer.js
> Optimize parameters parsing

- .github/workflows/node.js.yml
- package.json
BREAKING CHANGE: Drops support for EOL node 12 and 17.
Made changes in the same places as v5.0.0 when that dropped support for node 10: https://github.com/delvedor/find-my-way/commit/b1cf7cbc90199f8d532ec93cbbd317f0bc3001bd
> chore!: drop support for node 12 and 17

- index.js
- test/errors.test.js
Signed-off-by: Matteo Collina <hello@matteocollina.com>
Fixes https://github.com/fastify/fastify-static/issues/325
> Avoid creating both * and /* routes

- index.d.ts
- test/types/router.test-d.ts
With #246 the methods `del` and `empty` from the constraint storage object were removed from the documentation, since these two methods are not used anyway. However, they should then also be removed in the types.
I made it optional for now, since otherwise it would be a major change? In the next major release you could then remove them completely.
> make del and empty optional

- README.md
- index.js
- test/methods.test.js
- test/regex.test.js
The `off` method had some bugs.
```js
const router = require('find-my-way')()
router.on('GET', '/test', {}, (req, res) => {})
router.on('GET', '/test', { constraints: { host: 'example.com' } }, (req, res) => {})
router.off('GET', '/test', { host: 'example.com' })
router.prettyPrint() // is empty
```
or
```js
const router = require('find-my-way')()
router.on('GET', '/test', {}, (req, res) => {})
router.on('GET', '/test', { constraints: { host: 'example.com' } }, (req, res) => {})
router.off('GET', '/test', { host: 'test.de' }) // only removes the route without constraint
```
The `off` method now implements the following logic:
1. `router.off` is called without constraints: Any route matching the provided method and path are removed regardless of the constraints
2. `router.off` is called …
> fix matcher function in off method and fix regex tests

- README.md
- index.js
- package.json
- test/custom-querystring-parser.test.js
Solves issue: https://github.com/fastify/fastify/issues/4252
> feat: replace querystring with fast-querystring

- index.js
- test/issue-17.test.js
- test/issue-206.test.js
Fix https://github.com/fastify/fastify/discussions/4324#discussioncomment-3816685
> Fix double colon escaping in multi-parametrical node

- index.js
- lib/http-methods.js
- test/methods.test.js
- test/shorthands.test.js
I would like to use find-my-way in an environment other than Node.js environment (Hybrid, Browser, etc.)
There is no problem with other modules because browserify polyfills are implemented, but in the find-my-way library, METHODS is imported from the http module, and no alternative polyfills exist.
To work around that issue, declare METHODS as a constant within find-my-way instead of importing it from the http module.
> fix: using pre-defined http methods instead http module

- README.md
- custom_node.js
- index.js
- test/errors.test.js
- test/params-collisions.test.js
> feat: add multiple parametric nodes support

- README.md
- custom_node.js
- handler_storage.js
- index.d.ts
- index.js
- lib/pretty-print.js
- lib/strategies/http-method.js
- test/pretty-print-tree.test.js
- test/pretty-print.test.js
- test/routes-registered.test.js
- test/types/router.test-d.ts
Fix: #315, #316, #271, #82
Problem: `prettyPrint` builds trees from scratch with a different algorithm. You can't use it for debugging and you always need to keep real trees and printed trees synced. It's literally another small router nested into the big one.
Solution: don't emulate the trees. I added a new option to the `prettyPrint` function: `method`. If you pass it, fmw will print you an internal tree. If you don't pass it, fmw will create a new router, merge all trees with a constraint hack, and will print the merged tree.
The logic of `commonPrefix: false` will be a little bit different.
\+ a lot of bug fixing, refactoring
❗ It will require regenerating prettyPrint tests in Fastify. Mostly because of bug fixing.
cc @climba03003 @Eomm @mcollina
> feat: use internal trees for prettyPrint

- index.js
- test/methods.test.js
- test/routes-registered.test.js
- test/shorthands.test.js
- test/store.test.js
Cloned main today, tried `npm run test`, failed with a few errors that went away with `standard --fix` and one error that required change from `.map` to `.forEach`.
First contribution here but doesn't seem to have broken anything and  `npm run test` now running.
> chore: `npm run test` failing due to standard

- README.md
- index.d.ts
- index.js
- lib/node.js
- package.json
- test/find-route.test.js
- test/has-route.test.js
Close #332
Issue in fastify: https://github.com/fastify/fastify/issues/4866
> feat: add findRoute and hasRoute methods

- README.md
- index.js
- lib/url-sanitizer.js
- test/querystring.test.js
This PR comes from the discussion in the issue (https://github.com/fastify/fastify/issues/5050). I've added a new parameter that allows the `;` character to be used to separate path and query as before, but its default value is `false` to be fully compliant with the RFC
> feat: disable semicolon separator by default

- README.md
- index.d.ts
- index.js
- test/find-route.test.js
- test/types/router.test-d.ts
Closes #341 
The goal of this PR is to add dev params to the object returned from the `Router.findRoute` method as we do on the `Router.find`.
> feat(route): return route params on findRoute

- lib/handler-storage.js
- test/constraint.host.test.js
> Update contraint check to throw with 32 handlers

- index.js
- lib/constrainer.js
- lib/strategies/accept-host.js
- lib/strategies/accept-version.js
> feat: add node: prefix for assert

- .github/dependabot.yml
- .github/workflows/node.js.yml
Well. why are we not keeping our deps up to date?
> add dependabot.yml

- README.md
The `lookup` header was mistakenly wrapped with ` ```js `.
Also checked all other links in the table of contents.
> Fix header in README

- .github/workflows/node.js.yml
- lib/handler-storage.js
- lib/null-object.js
- test/null-object.test.js
see https://github.com/fastify/fastify/issues/4357
@eomm
@mcollina
@jsumners
I did not bench
> feat!: parameter object is null object

- index.js
Just improves consistency, everything other than `*` and `/` uses charCodeAt
> chore: prefer charCodeAt

- .github/workflows/node.js.yml
This PR:
-   Removes Git credentials after checkout as a security precaution by setting `persist-credentials` to false. They are not used after the initial checkout, and this stops them from accidentally leaking through a script; [see related GitHub security post](https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/) and [related actions/checkout issue](https://github.com/actions/checkout/issues/485)
-   Set `check-latest` to true, so that the `actions/setup-node` will check it is using the latest minor or hotfix Node version and use that instead of its cached version, this stops an issue like with 22.5.0 that introduced a regression and actions were still using that instead of 22.5.1
- Node 22.5.0 was why Windows 22 was excluded to begin with, which has now …
> ci(node.js): update workflow

- .github/workflows/node.js.yml
After what has been happening with [tj-actions/changed-files](https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised) over the past week this is probably a sensible idea.
[See related blog post by rafaelgss about pinning to the commit-hash](https://blog.rafaelgss.dev/why-you-should-pin-actions-by-commit-hash).
> ci(node.js): pin actions to commit-hash

- index.d.ts
- test/types/router.test-d.ts
missing the param done of lookup method
> fix: missing the param done of lookup method

- index.js
Before
```
lookup root "/" route.................................... x 48,077,482 ops/sec ±0.59% (589 runs sampled)
lookup short static route................................ x 31,420,706 ops/sec ±0.52% (592 runs sampled)
lookup long static route................................. x 9,783,174 ops/sec ±0.25% (595 runs sampled)
lookup long static route (common prefix)................. x 7,271,538 ops/sec ±0.36% (594 runs sampled)
lookup short parametric route............................ x 21,064,272 ops/sec ±0.32% (592 runs sampled)
lookup long parametric route............................. x 12,880,641 ops/sec ±0.36% (591 runs sampled)
lookup short parametric route (encoded unoptimized)...... x 12,994,657 ops/sec ±0.35% (593 runs sampled)
lookup short parametric route (encoded …
```
> perf: refactor escapeRegExp and removeDuplicateSlashes functions

- .github/workflows/node.js.yml
Most first party actions now use https://github.com/actions/publish-immutable-action, which negates the need for commit hashes.
> ci: use tags for immutable github actions
